-- Paises, no se que hacer para las descripciones
INSERT INTO Pais
    (nombre) VALUES
    ('Alemania'),
    ('Argentina'),
    ('Australia'),
    ('Brazil'),
    ('Canada'),
    ('Chile'),
    ('Colombia'),
    ('Francia'),
    ('India'),
    ('Indonesia'),
    ('Italia'),
    ('Japon'),
    ('Corea del Sur'),
    ('Mexico'),
    ('Peru'),
    ('Polonia'),
    ('Espana'),
    ('Turquia'),
    ('Estados Unidos'),
    ('Venezuela')
;


-- Paises, no se que hacer para las descripciones
INSERT INTO Ciudad
    (nombre, id_pais) VALUES
    ('Cologne', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Alemania')),
    ('Hamburg', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Alemania')),
    ('Munich', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Alemania')),
    ('Stuttgart', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Alemania')),
    ('Wuppertal', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Alemania')),
    ('Rosario', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Argentina')),
    ('Buenos Aires', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Argentina')),
    ('Cordoba', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Argentina')),
    ('Corrientes', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Argentina')),
    ('Santa Fe', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Argentina')),
    ('Adelaide', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Australia')),
    ('Perth', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Australia')),
    ('Brisbane', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Australia')),
    ('Canberra', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Australia')),
    ('Cranbourne', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Australia')),
    ('Sao Luis', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Brazil')),
    ('Campinas', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Brazil')),
    ('Rio de Janeiro', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Brazil')),
    ('Belem', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Brazil')),
    ('Guarulhos', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Brazil')),
    ('Ottawa', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Canada')),
    ('Edmonton', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Canada')),
    ('Calgary', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Canada')),
    ('Vancouver', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Canada')),
    ('Victoria', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Canada')),
    ('La Florida', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Chile')),
    ('Maipu', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Chile')),
    ('Puente Alto', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Chile')),
    ('Santiago', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Chile')),
    ('Concepcion', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Chile')),
    ('Barranquilla', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Colombia')),
    ('Cali', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Colombia')),
    ('Medellin', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Colombia')),
    ('Palmira', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Colombia')),
    ('Neiva', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Colombia')),
    ('Paris', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Francia')),
    ('Toulouse', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Francia')),
    ('Lyon', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Francia')),
    ('Marseille', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Francia')),
    ('Bordeaux', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Francia')),
    ('Bareilly', (SELECT id_pais FROM Pais WHERE nombre LIKE 'India')),
    ('Kota', (SELECT id_pais FROM Pais WHERE nombre LIKE 'India')),
    ('Raipur', (SELECT id_pais FROM Pais WHERE nombre LIKE 'India')),
    ('Jodhpur', (SELECT id_pais FROM Pais WHERE nombre LIKE 'India')),
    ('Vijayawada', (SELECT id_pais FROM Pais WHERE nombre LIKE 'India')),
    ('Bogor', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Indonesia')),
    ('Bandar Lampung', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Indonesia')),
    ('Cilacap', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Indonesia')),
    ('Batam Centre', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Indonesia')),
    ('Sumedang', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Indonesia')),
    ('Milan', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Italia')),
    ('Rome', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Italia')),
    ('Florence', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Italia')),
    ('Bologna', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Italia')),
    ('Genoa', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Italia')),
    ('Sendai', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Japon')),
    ('Hiroshima', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Japon')),
    ('Saitama', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Japon')),
    ('Kyoto', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Japon')),
    ('Osaka', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Japon')),
    ('Changwon', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Corea del Sur')),
    ('Goyang', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Corea del Sur')),
    ('Tongjin', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Corea del Sur')),
    ('Ulsan', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Corea del Sur')),
    ('Suwon', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Corea del Sur')),
    ('Morelia', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Mexico')),
    ('Ciudad Nezahualcoyotl', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Mexico')),
    ('Nezahualcoyotl', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Mexico')),
    ('Mexicali', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Mexico')),
    ('Juarez', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Mexico')),
    ('Arequipa', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Peru')),
    ('Lima', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Peru')),
    ('Iquitos', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Peru')),
    ('Huancayo', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Peru')),
    ('Callao', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Peru')),
    ('Warsaw', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Polonia')),
    ('Szczecin', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Polonia')),
    ('Gdansk', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Polonia')),
    ('Poznan', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Polonia')),
    ('Lodz', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Polonia')),
    ('Sevilla', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Espana')),
    ('Valencia', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Espana')),
    ('Barcelona', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Espana')),
    ('Santa Cruz', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Espana')),
    ('Palma', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Espana')),
    ('Denizli', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Turquia')),
    ('Balikesir', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Turquia')),
    ('Samsun', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Turquia')),
    ('Kayseri', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Turquia')),
    ('Istanbul', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Turquia')),
    ('Memphis', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Estados Unidos')),
    ('Richmond', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Estados Unidos')),
    ('Raleigh', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Estados Unidos')),
    ('Salt Lake City', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Estados Unidos')),
    ('Nashville', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Estados Unidos')),
    ('San Cristobal', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Venezuela')),
    ('Barquisimeto', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Venezuela')),
    ('Valencia', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Venezuela')),
    ('Maracaibo', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Venezuela')),
    ('Caracas', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Venezuela'))
;


-- Usuario, falta id_ciudad
INSERT INTO Usuario
    (sexo, nombre, email, fecha_nacimiento, nombre_usuario, constrasena, tarjeta, apellido, id_ciudad) VALUES
    ('M', 'Aristotle', 'apendre0@desdev.cn', '1980-05-08', 'apendre0', '$2a$04$MDSUGHSNaGjRgGKgaNHs2eq3k5/ge.mLwpKul2tlOLzHZIeS4x.WG', '5610034195179049', 'Pendre', (SELECT id_ciudad FROM Ciudad WHERE name LIKE '')),
    ('F', 'Isadora', 'ipashler1@is.gd', '1973-12-08', 'ipashler1', '$2a$04$JS4Zkz7gqJWl/UgUYTk/GOTCPWijv0yKMejhgicTCGYklLeV8kWY.', '6771566613558594137', 'Pashler', (SELECT id_ciudad FROM Ciudad WHERE name LIKE '')),
    ('F', 'Tierney', 'tovendon2@furl.net', '1994-09-10', 'tovendon2', '$2a$04$D7WxVJR6b2krANo.wQFIA.h.9VEqN7OpMC/6YyS6pS51TML058MA2', '5010129022211928', 'Ovendon', (SELECT id_ciudad FROM Ciudad WHERE name LIKE '')),
    ('F', 'Angie', 'acellier3@diigo.com', '1996-12-10', 'acellier3', '$2a$04$79eX70F2dZqtK55RTRAg1.K6XiAK/Z732xKtMExy7O/nAJ2jYmYR.', '6759044056761978456', 'Cellier', (SELECT id_ciudad FROM Ciudad WHERE name LIKE '')),
    ('F', 'Amitie', 'atrett4@nature.com', '2005-10-26', 'atrett4', '$2a$04$W2N1hIqdhqj.v3DyiezPie4u57CPAlCkd3nD7Wq8hMm7hYjyeMgUK', '633464499769468522', 'Trett', (SELECT id_ciudad FROM Ciudad WHERE name LIKE '')),
    ('F', 'Deeann', 'dbotler5@pagesperso-orange.fr', '1974-02-02', 'dbotler5', '$2a$04$gfWRT72Ui.JxhNv5NG6wTumdtEPWvEyKGIYjWChKHlXWM00ITaXy2', '201851581475905', 'Botler', (SELECT id_ciudad FROM Ciudad WHERE name LIKE '')),
    ('M', 'Aluino', 'acoggen6@newyorker.com', '1986-03-13', 'acoggen6', '$2a$04$iEz/AaNRmBcmZnssGdZxquhWLvawHGuL981sGO79Hxb/StMcfOy6u', '5499340638988862', 'Coggen', (SELECT id_ciudad FROM Ciudad WHERE name LIKE '')),
    ('F', 'Merci', 'mmcgoldrick7@clickbank.net', '1983-03-15', 'mmcgoldrick7', '$2a$04$ZSCOPyP4njY71Ohc18l4Qe38AnppB0sYrdPqetqJDMTdV/IuYGO6C', '4844183108634201', 'McGoldrick', (SELECT id_ciudad FROM Ciudad WHERE name LIKE '')),
    ('M', 'Car', 'ccoleshill8@pcworld.com', '1992-05-22', 'ccoleshill8', '$2a$04$TacQv6tYM2iUZw4RgixiyOaVamjYpt1FSMMkNtzHf/k.YNeDW/Rri', '3545175070063645', 'Coleshill', (SELECT id_ciudad FROM Ciudad WHERE name LIKE '')),
    ('F', 'Euphemia', 'esandyford9@wiley.com', '2006-04-21', 'esandyford9', '$2a$04$8Gy0WvHW2YuXqUansJmD.eVhyiPNCuiVAxGaL0hpWoKG1UfcWYWwu', '3537627950364006', 'Sandyford', (SELECT id_ciudad FROM Ciudad WHERE name LIKE '')),
    ('F', 'Rasia', 'rweaversa@mozilla.org', '1976-05-20', 'rweaversa', '$2a$04$0VBQ6hwP9hNCWevN3WPulOVZzOUzvsKEgd19jsDQ7Fg7w0qFYDf2W', '58933841435699084', 'Weavers', (SELECT id_ciudad FROM Ciudad WHERE name LIKE '')),
    ('M', 'Cazzie', 'cackerleyb@pen.io', '1996-07-04', 'cackerleyb', '$2a$04$32Xfo1i/V/gks/RrFIeDO.DaTnrPPUSgp6A4hL4EIu0FZOqLpqYii', '4857794782846', 'Ackerley', (SELECT id_ciudad FROM Ciudad WHERE name LIKE '')),
    ('M', 'Donaugh', 'dminneyc@github.io', '1990-05-19', 'dminneyc', '$2a$04$Y4N8SGV8lBxFjYz.9pHTw.Ee5q6euquESjrpcabXoiA4Qyt0GoYVS', '3533859649294625', 'Minney', (SELECT id_ciudad FROM Ciudad WHERE name LIKE '')),
    ('F', 'Jaynell', 'jbayfieldd@ning.com', '2003-06-02', 'jbayfieldd', '$2a$04$J65Eq1wpXa6o82r39aAJr.1qirqgtvL22UQaNW.MZmc3Z8CaWN9tS', '374622788212610', 'Bayfield', (SELECT id_ciudad FROM Ciudad WHERE name LIKE '')),
    ('N/A', 'Lorianna', 'lwarnese@alexa.com', '1990-11-06', 'lwarnese', '$2a$04$HstnE5mppkk6SdU8/S7vle//safpEMqlaNQInBmygJ5sJj6O4IOre', '201538976246294', 'Warnes', (SELECT id_ciudad FROM Ciudad WHERE name LIKE '')),
    ('M', 'Fletcher', 'fbeaushawf@studiopress.com', '1993-03-09', 'fbeaushawf', '$2a$04$4xCVUrzpfBxOnUedgL6OeOefwEQxaCIdWGmkscd0LoBnVJT4pZ/gG', '3555720299240750', 'Beaushaw', (SELECT id_ciudad FROM Ciudad WHERE name LIKE '')),
    ('M', 'Waring', 'wmeadowcraftg@imdb.com', '1987-01-05', 'wmeadowcraftg', '$2a$04$bsFegA9DYO0ThKVfv3C9AuBl0plsNXsxqYnE6kPxrVgGJJ8EJ7Y/6', '3540631307444359', 'Meadowcraft', (SELECT id_ciudad FROM Ciudad WHERE name LIKE '')),
    ('F', 'Bunni', 'bcrabbeh@last.fm', '1997-04-10', 'bcrabbeh', '$2a$04$JTYGM45XA531v51ydmP8AO8z88rhO9RgEmIHpKQXYSF2wjrIjJxF2', '5020027073174227', 'Crabbe', (SELECT id_ciudad FROM Ciudad WHERE name LIKE '')),
    ('F', 'Maddalena', 'mvaughni@wix.com', '2003-02-24', 'mvaughni', '$2a$04$4AkeccIkifwYkTsBC.cWEODjhLN.kUl7xXF9CEVGR19M.3NwBdgGi', '5048373871169680', 'Vaughn', (SELECT id_ciudad FROM Ciudad WHERE name LIKE '')),
    ('F', 'Willabella', 'wrobakj@parallels.com', '1977-11-29', 'wrobakj', '$2a$04$BVgLrD5W/rwsdCgViYi7PuxA8t1D.aD8kQz6aLp.3OX/FGCAF68D6', '4041377988061011', 'Robak', (SELECT id_ciudad FROM Ciudad WHERE name LIKE '')),
    ('F', 'Liane', 'lbaldettik@printfriendly.com', '1990-10-09', 'lbaldettik', '$2a$04$T8QBDoT602BcuPLxRZDGUeIzh30f6gjKh5rgtPKCcffHEhpE8Sv0O', '374283544948375', 'Baldetti', (SELECT id_ciudad FROM Ciudad WHERE name LIKE '')),
    ('F', 'Zorah', 'zmabbotl@wp.com', '1973-09-07', 'zmabbotl', '$2a$04$fJaOziyq.hNlBxRyOgV7ROPcjGOWajZl463zTenJrr2aEBZeDMHwa', '4026587283064788', 'Mabbot', (SELECT id_ciudad FROM Ciudad WHERE name LIKE '')),
    ('F', 'Emelina', 'elittledykem@sohu.com', '2006-10-27', 'elittledykem', '$2a$04$jpvtF6At.udOLmCM2HZl6enleD4J85S/fB2DlhIBRNWP1w2hbQoWC', '3581685692770356', 'Littledyke', (SELECT id_ciudad FROM Ciudad WHERE name LIKE '')),
    ('M', 'Axel', 'akenann@eepurl.com', '1996-10-09', 'akenann', '$2a$04$M7YTjtQVZZ716KEQNVE5N.722hfhduxbpq/.AU77T9cLt0rqKTg32', '3566342456809629', 'Kenan', (SELECT id_ciudad FROM Ciudad WHERE name LIKE '')),
    ('F', 'Florella', 'fhowato@quantcast.com', '1971-02-18', 'fhowato', '$2a$04$hiU86PedlQ0C4sKwDVFhvuWxZqkhDshWF1e5YikMtJUMm/95vEp.e', '3547025375251304', 'Howat', (SELECT id_ciudad FROM Ciudad WHERE name LIKE '')),
    ('F', 'Florentia', 'ftembeyp@nature.com', '1984-10-19', 'ftembeyp', '$2a$04$T/Be0egoY1SoCZ50k4ZrGO13l43eDpBZBYMgQbbKebmTMyka4e9yC', '3574561614698695', 'Tembey', (SELECT id_ciudad FROM Ciudad WHERE name LIKE '')),
    ('M', 'Wilbur', 'wnultyq@blogtalkradio.com', '1973-07-22', 'wnultyq', '$2a$04$cY4WVVri7XWjoG7OAi5OG.K0wLD9nWDxbX7mOTVJO.njxBcD8smEq', '3551683367325727', 'Nulty', (SELECT id_ciudad FROM Ciudad WHERE name LIKE '')),
    ('M', 'Archibold', 'ahenstoner@jalbum.net', '2000-04-04', 'ahenstoner', '$2a$04$a0pSgviSmGgkpyMdQDlEqetvZuaNBjX5Xo9cCs6lpzrmRNHd8rX8.', '5100177919155931', 'Henstone', (SELECT id_ciudad FROM Ciudad WHERE name LIKE '')),
    ('F', 'Catina', 'cwallbrooks@cmu.edu', '1995-12-11', 'cwallbrooks', '$2a$04$ADPrlbGM4zmyrbMuenngie2PxTqfFl.doQQka2vASENwirtguZIpS', '3540731586675812', 'Wallbrook', (SELECT id_ciudad FROM Ciudad WHERE name LIKE '')),
    ('N/A', 'Zacharia', 'znealont@baidu.com', '1987-08-30', 'znealont', '$2a$04$OdVJe91aK2t7cBx/u/OOheZ1YsR7sghJPnuvFQ8NmOrT.Jiy2Hyp6', '67612151184204675', 'Nealon', (SELECT id_ciudad FROM Ciudad WHERE name LIKE ''))
;


-- Perfil
INSERT INTO Perfil
    (id_usuario, nombre, email, preferencias_idioma) VALUES
    ((SELECT id_usuario FROM Usuario WHERE nombre='Aristotle'), 'Lesli', 'lpolgreen0@domainmarket.com', 'Irish Gaelic'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Isadora'), 'Genia', 'gvandenvelden1@networkadvertising.org', 'Dari'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Tierney'), 'Ollie', 'oormistone2@blinklist.com', 'Kashmiri'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Angie'), 'Ky', 'kwakenshaw3@state.tx.us', 'Thai'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Amitie'), 'Rebbecca', 'rbresson4@kickstarter.com', 'Thai'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Axel'), 'Eliot', 'erenihan5@bandcamp.com', 'Albanian'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Axel'), 'Hester', 'hdavley6@noaa.gov', 'Tetum'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Deeann'), 'Horten', 'hfeatenby7@icio.us', 'Tsonga'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Deeann'), 'Yolane', 'ydorsett8@twitter.com', 'Mongolian'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Deeann'), 'Torrence', 'trichin9@china.com.cn', 'Filipino'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Florella'), 'Carri', 'cdownera@ihg.com', 'Amharic'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Florella'), 'Jolie', 'jsnarb@nyu.edu', 'Chinese'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Aluino'), 'Demeter', 'dbrinkworthc@ning.com', 'Hiri Motu'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Aluino'), 'Marilyn', 'mbuddingtond@wikia.com', 'German'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Florentia'), 'Martainn', 'mgiacovellie@flavors.me', 'Burmese'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Florentia'), 'Lauree', 'lmacairtf@networksolutions.com', 'Amharic'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Merci'), 'Berta', 'bshinefieldg@uiuc.edu', 'Malay'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Merci'), 'Fredia', 'fstonemanh@deviantart.com', 'Estonian'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Wilbur'), 'Henrik', 'hmancktelowi@state.gov', 'Burmese'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Wilbur'), 'Wiatt', 'wpriddiej@time.com', 'Malagasy'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Car'), 'Avictor', 'ashillittok@noaa.gov', 'Dhivehi'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Car'), 'Alena', 'afilippovl@bluehost.com', 'Assamese'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Car'), 'Frederico', 'fbarajazm@cyberchimps.com', 'Northern Sotho'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Euphemia'), 'Ally', 'acolletonn@geocities.com', 'Dhivehi'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Euphemia'), 'Cornie', 'cconrarto@nifty.com', 'Dzongkha'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Euphemia'), 'Helaine', 'hmeeusp@parallels.com', 'Kashmiri'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Euphemia'), 'Obie', 'oelphq@addthis.com', 'Aymara'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Euphemia'), 'Franklin', 'felphickr@princeton.edu', 'Malay'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Rasia'), 'Aurel', 'ameggisons@unicef.org', 'Thai'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Rasia'), 'Rriocard', 'rdearnlyt@tamu.edu', 'Lao'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Archibold'), 'Chiarra', 'ccampeyu@photobucket.com', 'Ndebele'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Archibold'), 'Alene', 'ascipseyv@sogou.com', 'Bosnian'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Cazzie'), 'Nickola', 'nhowlew@oakley.com', 'Guaraní'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Cazzie'), 'Gayla', 'gmcsaulx@tripod.com', 'Thai'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Donaugh'), 'Vale', 'vharriesy@wisc.edu', 'Lithuanian'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Donaugh'), 'Vernon', 'vstoodz@tripod.com', 'Dzongkha'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Catina'), 'Gaile', 'gmeeny10@pagesperso-orange.fr', 'Bulgarian'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Catina'), 'Claudette', 'cpepall11@harvard.edu', 'French'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Jaynell'), 'Putnam', 'pacomb12@cnbc.com', 'Luxembourgish'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Jaynell'), 'Datha', 'ddelaeglise13@auda.org.au', 'Malagasy'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Lorianna'), 'Winfield', 'wbarsam14@webeden.co.uk', 'Portuguese'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Lorianna'), 'Dewey', 'djouning15@acquirethisname.com', 'Hiri Motu'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Zacharia'), 'Karney', 'kfricker16@privacy.gov.au', 'Papiamento'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Zacharia'), 'Florencia', 'fdametti17@altervista.org', 'English'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Fletcher'), 'Linc', 'lblankett18@bloglines.com', 'Polish'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Fletcher'), 'Kristan', 'kpawelec19@macromedia.com', 'Albanian'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Waring'), 'Foster', 'fbulle1a@hexun.com', 'Macedonian'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Waring'), 'Cynthie', 'cspehr1b@flavors.me', 'Swedish'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Bunni'), 'Ninette', 'ndeware1c@github.io', 'Icelandic'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Bunni'), 'Adan', 'ahobell1d@imageshack.us', 'Swahili'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Maddalena'), 'Myrvyn', 'mrainey1e@ocn.ne.jp', 'Japanese'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Maddalena'), 'Jennilee', 'jcottu1f@wikipedia.org', 'Hebrew'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Willabella'), 'Kati', 'kpentony1g@deliciousdays.com', 'Zulu'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Willabella'), 'Onfroi', 'oroberts1h@nymag.com', 'Chinese'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Liane'), 'Axe', 'aedelheit1i@barnesandnoble.com', 'Persian'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Liane'), 'Penelopa', 'planfranconi1j@japanpost.jp', 'Icelandic'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Zorah'), 'Misha', 'mribeiro1k@mit.edu', 'Lao'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Zorah'), 'Woodrow', 'wsmy1l@networkadvertising.org', 'Korean'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Emelina'), 'Rae', 'rvern1m@gmpg.org', 'Indonesian'),
    ((SELECT id_usuario FROM Usuario WHERE nombre='Emelina'), 'Evanne', 'epaylie1n@friendfeed.com', 'Somali'),
;

    
-- Contenido
INSERT INTO Contenido
    (annio_lanzamiento, nombre, es_contenido_original) VALUES
    (2008, 'Breaking Bad', FALSE),
    (2018, 'Cobra Kai', TRUE)
;


-- Serie
INSERT INTO Serie
    (id_contenido, num_episodios, descripcion) VALUES
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), 62, 'Un profesor de Química de secundaria con cáncer terminal se asocia a un exestudiante para asegurar el futuro de su familia al fabricar y vender metanfetamina.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), 60, 'Enemigos acérrimos. Dojos rivales. Sangre nueva. Daniel y Johnny reviven viejas rivalidades en esta secuela de las películas de «Karate Kid».')
;


-- Temporada, usar get_season
INSERT INTO Temporada
    (id_contenido, numero, descripcion) VALUES
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), 1,'A medida que Walter construye su imperio, su esposa empieza a sospechar de su errática conducta, y la DEA inicia la búsqueda de un nuevo líder de la droga.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), 2,'Walter y Jesse, llegan alto en el juego de las drogas, llamando la atención del cartel rival y poniendo en peligro a Hank; cuñado de Walter y agente de la DEA.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), 3,'Pensando en su familia, Walter sigue cocinando metanfetamina en secreto. Mientras, Jesse, ex alumno de Walter, se ha hecho adicto a la heroína.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), 4,'Bryan Cranston regresa en una nueva temporada como Walter White, quien sigue elaborando metanfetaminas e intentando superar al narcotraficante Gus Fring.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), 5,'En la temporada final, Walt ya no tiene que esforzarse por ser malo. Su vida sigue en una espiral descendente que le lleva a lo más alto de un imperio de la droga.'),

    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), 1,'Décadas después del torneo que les cambió la vida, se reaviva la rivalidad entre Johnny y Daniel. Esta secuela continúa la historia de las películas de Karate Kid.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), 2,'Johnny intenta construir una nueva vida, pero alguien del pasado podría alterar su futuro. Daniel abre su Miyagi-do para competir contra Cobra Kai.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), 3,'Con un nuevo sensei al mando del dojo de la serpiente, las batallas se libran en tres frentes. Al igual que Cobra Kai, las viejas rencillas nunca mueren...'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), 4,'Daniel y Johnny deciden unir fuerzas para enfrentar a un enemigo en común, y Kreese busca un aliado en el pasado.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), 5,'Mientras Terry conduce a Cobra Kai hacia un nuevo régimen, Daniel, Johnny y un viejo aliado unen sus fuerzas en una batalla que va más allá del dojo.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), 6,'El mundial de karate se acerca, y Daniel y Johnny trabajan para rearmar el equipo. Pero viejos enemigos y nuevos peligros minan el camino a la gloria.')
;

-- Episodio, usar get_episode
INSERT INTO Episodio
    (id_contenido, id_temporada, numero, nombre, descripcion) VALUES
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=1), 1, 'Principio del fin', 'Un profesor de química de escuela secundaria recurre a la venta de drogas para mantener a su familia.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=1), 2, 'El gato en la bolsa', 'Luego del fracaso de su primer negocio de drogas, Walt y Jesse deben deshacerse de dos cadáveres. Skyler sospecha que su marido no está involucrado en nada bueno.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=1), 3, 'Y la bolsa en el río', 'Mientras Walt limpia el desorden que quedó tras su primer negocio de drogas, piensa en decirle a Skyler la verdad sobre su enfermedad.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=1), 4, 'Cáncer', 'Al ser forzado a contar la verdad acerca de su enfermedad, Walt enfrenta el problema de cómo pagar una serie de caros tratamientos contra el cáncer.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=1), 5, 'Materia gris', 'Skyler organiza una intervención para convencer a Walt de que acepte la generosa oferta de su excompañero de investigaciones de pagar el tratamiento contra el cáncer.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=1), 6, 'Un loco puñado de nada', 'Los efectos secundarios y el costo del tratamiento crecen, y Walt exige que Jesse encuentre un revendedor para sus drogas; Jesse termina en problemas con un exconvicto.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=1), 7, 'Acuerdo no violento', 'Tras el encuentro cercano de Jesse con la muerte, Walt acepta producir más drogas para Tuco, mientras Skyler sospecha que su hermana robó un costoso regalo para bebés.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=2), 1, 'Siete con treinta y siete', 'Cuando preparan los planes para su gran negocio final de drogas, a Walt y Jesse les preocupa que a Tuco se le ocurra matarlos cuando quiera.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=2), 2, 'A las brasas', 'Mientras la DEA pone en marcha la búsqueda de Tuco, Skyler recurre a Hank para que la ayude a encontrar a Walt.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=2), 3, 'Picadura de una abeja muerta', 'Walt intenta volver a acercarse a Skyler, y Jesse se encuentra sin hogar después de que sus padres lo echan de su casa.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=2), 4, 'Abajo', 'Walt lucha por intentar salvar su relación con Skyler, y Jesse se queda sin hogar cuando sus padres lo desalojan.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=2), 5, 'Rotura', 'Hank trata de recobrar la compostura tras su encuentro con Tuco. Mientras, Jesse forma una pandilla para distribuir más producto por la ciudad.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=2), 6, 'Cucú', 'Jesse busca a los adictos que robaron las drogas a Skinny Pete, y Walt lucha por sostener su coartada para explicar cómo ha pagado el tratamiento de cáncer.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=2), 7, 'Negro y azul', 'La reputación de narco implacable de Jesse lleva a Walt a ampliar sus actividades; la incursión de Hank en el mundo de la oficina de la DEA en El Paso lo estremece.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=2), 8, '¡Llama a Saul!', 'El arresto de Badger obliga a Walt y Jesse a contratar a un abogado de mala reputación.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=2), 9, 'Cuatro días afuera', 'Preocupado porque no le queda mucha vida, Walt intenta cubrir las necesidades de su familia en una maratónica sesión de preparación de metanfetamina con Jesse.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=2), 10, 'Terminado', 'Al recibir buenas noticias sobre el tratamiento de cáncer, Walt acude a su cuñado, Hank, antes de centrar su atención en hacer las cosas bien en su hogar.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=2), 11, 'Mandala', 'Skyler tiene conflictos por sus sentimientos hacia su jefe. La muerte de un vendedor callejero fuerza a Walt a buscar otro lugar para vender la metanfetamina.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=2), 12, 'Phoenix', 'Walt intenta encaminar su vida y la de Jesse mientras se prepara para la cirugía y pretende esconder la procedencia de su dinero a Skyler y Walt Jr.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=2), 13, 'ABQ', 'Walt intenta encaminar su vida y la de Jesse mientras se prepara para la cirugía y pretende esconder la procedencia de su dinero a Skyler y Walt Jr.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=3), 1, 'No más', 'Tras el desastre aéreo de Albuquerque, Skyler obliga a Walt a mudarse, mientras la estadía de Jesse en rehabilitación lo ayuda a aceptar su rol en el fatal choque aéreo.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=3), 2, 'Caballo sin nombre', 'Skyler está decidida a divorciarse, y Walt acaba en la mira de dos asesinos de un cártel mexicano que buscan venganza.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=3), 3. T. S, 'T.', 'Jesse se cuestiona volver al negocio de las drogas ya que una organización de narcotraficantes espera con ansias vengar la muerte de uno de sus miembros.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=3), 4, 'Luz verde', 'Mientras el romance de Skyler con su jefe crea caos en su matrimonio, un lote de metanfetamina que devuelve a Jesse al negocio involucra inadvertidamente a Walt.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=3), 5, 'Más', 'Walt considera una oferta para regresar al narcotráfico; la obsesión de Hank por atrapar a "Heisenberg" trae problemas para Jesse.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=3), 6, 'Atardecer', 'Walt vuelve al narcotráfico en el laboratorio de Gus, pero el descubrimiento de su vieja casa rodante lo fuerza a él y a Jesse a actuar para que Hank no los descubra.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=3), 7, 'Un minuto', 'Hank, enojado, arriesga su carrera al atacar a Jesse; Walt, preocupado de que Jesse hable, le da un lugar en su laboratorio.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=3), 8, 'Te veo', 'Mientras Hank se aferra a la vida, Walt descubre que los matones pueden estar tras él y busca alejarse de los problemas tomando a Jesse como compañero.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=3), 9, 'Kafkiano', 'Al retomar la producción junto a Walt, Jesse piensa cómo aumentar las ganancias; la recuperación de Hank pone a Marie en una situación difícil con la compañía de seguros.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=3), 10, 'Vuelo', 'Walt y Jesse se enfrentan a una larga noche en el laboratorio... y a una fastidiosa mosca.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=3), 11, 'Abiquiú', 'Hank no está contento con su recuperación; Skyler cuestiona el negocio de lavado de dinero de Saul, y Jesse se enamora de una compañera de rehabilitación.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=3), 12, 'Medias medidas', 'Jesse va tras los narcos que mataron a Combo, Hank se niega a dejar el hospital y Skyler presiona a Walt para que acepte el negocio de lavado de dinero.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=3), 13, 'Medidas totales', 'Luego de liquidar a dos traficantes de su jefe, Walt se da cuenta de que Gus planea matarlo y reemplazarlo con su anterior asistente.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=4), 1, 'Navaja', 'Después de luchar por sus vidas en una turbulenta situación, Walt y Jesse esperan con ansiedad la próxima jugada de Gus.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=4), 2, 'Revólver calibre 38', 'Mientras Walt prepara su defensa contra Gus, Jesse hace frente a la presión renovando su amistad con Badger y Skinny Pete.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=4), 3, 'Casa abierta', 'Mientras Walt se preocupa acerca de la intromisión de Gus y la salud mental de Jesse, cada vez más frágil, Skyler aumenta la presión para obtener lo que quiere.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=4), 4, 'Puntos clave', 'Mientras Skyler arma una historia elaborada para explicar las finanzas de los White, Walt, preocupado, descubre que Hank ha comenzado una nueva investigación.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=4), 5, 'Copiloto', 'Jesse acompaña como copiloto a Mike en una riesgosa serie de picadas, lo que hace que Walt se preocupe por la posible muerte de su socio.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=4), 6, 'Arrinconados', 'Skyler adopta un enfoque reservado cuando sospecha que Walt no le está diciendo la verdad. Mientras tanto, Jesse prueba su valía ante Mike y Gus.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=4), 7, 'Perro problemático', 'Obligado a devolver el auto que compró para su hijo, Walt responde poniendo en aprietos a Skyler con su nueva operación de lavado de dinero.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=4), 8, 'Hermanos', 'Cuando Hank presenta evidencia de que Gus es el narcotraficante de metanfetamina de Albuquerque, a Walt le preocupa que los maten a él y a Jesse por proteger a su jefe.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=4), 9, 'Micrófono', 'Mientras Walt intenta subvertir la investigación de Hank sobre la escena de Albuquerque, una advertencia mortal fuerza a Gus a considerar un trato con el cártel mexicano.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=4), 10, 'Salud', 'Mientras Walt, maltratado, aún se recupera de la pelea, Gus se lleva a Jesse con él a México para cerrar un trato con el cártel.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=4), 11, 'Entrepiso', 'Mientras Skyler presiona a Ted para que acepte su dinero y pueda pagar los impuestos, Gus sostiene que Jesse debería reanudar su trabajo en el laboratorio él solo.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=4), 12, 'Fin de los tiempos', 'Mientras le ordena a su familia que aproveche la protección que la DEA le ofrece a Hank, Walt espera el destino que le toque.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=4), 13, 'Cara a cara', 'Cuando su plan de matar a Gus fracasa, Walt y Jesse deben actuar rápido para cubrir sus rastros y evitar la muerte.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=5), 1, 'Vive libre o muere', 'Walt visita a su familia, que aún está en custodia, mientras debe lidiar con las secuelas de la explosión en Casa Tranquila.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=5), 2, 'Madrigal', 'Walt y Jesse deciden buscar un nuevo compañero para que los ayude en su último proyecto, y la DEA investiga varias pistas con la esperanza de encontrar algo certero.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=5), 3, 'Peligro', 'Para consternación de Skyler, Walter vuelve a vivir a la casa. Walter, Mike y Jesse se reúnen con Saul para pedirle que les encuentre un nuevo lugar para cocinar.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=5), 4, '51 (Cincuenta y uno)', 'Lydia se ve forzada a entregar a su propio empleado a la DEA, y Mike le ofrece un reemplazante: Jesse. Walt y Skyler discuten sobre si la familia corre peligro.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=5), 5, 'Carga de muerte', 'Mike y Lydia trabajan para transportar la metilamina necesaria para la operación. Walt y Jesse intentan elaborar un plan que no arruine su tapadera.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=5), 6, 'Adquisición', 'Walt, Mike y Jesse lidian con las repercusiones del robo de la metilamina. Mike y Jesse quieren salirse del negocio, pero Walt está decidido a construir su imperio.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=5), 7, 'Di mi nombre', 'Walter intenta iniciar un trato con Declan, y Hank —quien tuvo que dejar ir a Mike— ahora tiene en la mira al abogado que ha estado pagando a los hombres de Mike.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=5), 8, 'Planeando sobre todos', 'Walt se encuentra con Lydia para conseguir los nombres de la gente de Mike que está en la cárcel. Skyler hace otro intento por convencer a Walt de que deje de cocinar.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=5), 9, 'Dinero sangriento', 'A medida que Walt y Jesse se adaptan a la vida fuera del negocio, Hank se aferra a una inquietante pista.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=5), 10, 'Enterrado', 'Mientras el pasado atormenta a Skyler, Walt cubre sus huellas, y Jesse continúa luchando con la culpa.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=5), 11, 'Confesiones', 'Jesse decide hacer un cambio, y Walt y Skyler intentan lidiar con una exigencia inesperada.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=5), 12, 'Perro rabioso', 'Una extraña estrategia comienza a dar frutos, mientras se ponen en marcha planes que podrían darle un giro completo a la situación.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=5), 13, 'Tohajiilee', 'La presión aumenta para Walt, de un modo que nunca habría esperado.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=5), 14, 'Ozymandias', 'Todos deben enfrentar circunstancias radicalmente distintas. Todos, sin excepción.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=5), 15, 'Pizarra de granito', 'Los sucesos que se iniciaron hace mucho tiempo marchan hacia una conclusión.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Breaking Bad'), (SELECT id_temporada FROM Temporada WHERE numero=5), 16, 'Felina', 'El final de la serie.'),

    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=1), 1, 'As degenerado', 'Alcohólico y harto de vivir a la sombra de Daniel, su antiguo rival, Johnny toca fondo y decide reabrir el dojo de karate Cobra Kai.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=1), 2, 'Golpear primero', 'Daniel ve el nuevo dojo Cobra Kai, y eso le trae recuerdos dolorosos. Más tarde, se entera de que Kyler, el chico que le gusta a Sam, fue atacado por un karateca.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=1), 3, 'Esqueleto', 'Con la idea de vigilar a Sam, Daniel se ofrece como chaperón para el baile de Halloween. Johnny intenta conseguir más alumnos para su flamante proyecto.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=1), 4, 'Cobra Kai nunca muere', 'Alguien arruina uno de los carteles de Daniel. La madre de Miguel le prohíbe practicar karate a su hijo, y Johnny recibe una llamada preocupante de la escuela de Robby.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=1), 5, 'Contrapeso', 'Una nueva alumna se suma a Cobra Kai. Entretanto, Daniel piensa en la forma de vengarse de Johnny. Kyler traiciona a Sam, y Miguel la defiende en la escuela.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=1), 6, 'Temblor', 'Tras la pelea de Miguel, se inscriben más alumnos en Cobra Kai, pero Johnny no los recibe de la mejor manera. Para herir a su padre, Robby empieza a trabajar con Daniel.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=1), 7, 'All Valley', 'Johnny debe persuadir al comité del torneo de levantar la prohibición impuesta a Cobra Kai, pero Daniel es uno de los miembros. Miguel y Sam tienen una cita.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=1), 8, 'Muda', 'Mientras Johnny prepara a sus alumnos para el torneo de All Valley, Daniel empieza a entrenar a Robby en el Miyagi-do sin saber que es el hijo de Johnny.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=1), 9, 'Diferentes pero iguales', 'Una discusión hace que Johnny y Daniel revivan el pasado. Los alumnos de Cobra Kai planean vengarse de los chicos populares.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=1), 10, 'Piedad', 'Antes del torneo, Johnny les enseña a sus alumnos la tercera regla de Cobra Kai: sin piedad. Alguien inesperado regresa a la vida de Johnny.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=2), 1, 'Piedad (Parte 2)', 'A pesar de la victoria de Cobra Kai, Johnny quiere cambiar el rumbo del dojo. Daniel abre su propia escuela con dos alumnos: Sam y Robby.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=2), 2, 'Otra vez juntos', 'Daniel les enseña a Sam y a Robby a encontrar el equilibrio. Johnny impresiona a Kreese con una técnica de entrenamiento creativa pero riesgosa.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=2), 3, 'Hielo y fuego', 'Cuando Miguel descubre que Robby es hijo de Johnny, el sensei reconoce sus falencias paternales. En busca de más alumnos, Daniel hace una demostración en un festival.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=2), 4, 'La hora de la verdad', 'Daniel sigue intentando promocionar el Miyagi-do, pero Cobra Kai es el centro de atención. Johnny sospecha que Kreese exagera sus logros.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=2), 5, 'Darlo todo', 'Después de que Eli desafía a Demetri en el centro comercial, Daniel ayuda a Demetri a tener confianza en sí mismo. Johnny se entera de que Robby está viviendo con Daniel.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=2), 6, 'Echa un vistazo a tu derecha', 'Los nuevos alumnos de Daniel aprenden a conciliar sus diferencias. Mientras Johnny disfruta de un viaje con amigos, Kreese impone su autoridad en el dojo.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=2), 7, 'Calma', 'Aunque cada sensei tiene su propio estilo, ambos prueban nuevas técnicas. Johnny confronta a Kreese, y la pasión de Daniel por el Miyagi-do pone en peligro su negocio.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=2), 8, 'Glory of Love', 'A medida que se enciende el romance secreto entre Sam y Robby, se enfría la relación entre Daniel y Amanda. Johnny intenta hallar el amor con ayuda de la tecnología.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=2), 9, 'Pulpo', 'Tras un encuentro imprevisto, Johnny y Daniel deciden darse una tregua. Por el contrario, la tensión acumulada entre los alumnos de ambos se descontrola en una fiesta.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=2), 10, 'Sin piedad', 'El primer día de clases, la rencilla entre Tory y Sam termina explotando en un enfrentamiento de karate que acapara la atención de toda la escuela.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=3), 1, 'Repercusiones', 'Mientras Miguel lucha por su vida y Robby está desaparecido, la comunidad de West Valley no duda en expresar su descontento con lo ocurrido... y con Daniel y Johnny.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=3), 2, '¿La herencia es más fuerte?', 'Daniel y Johnny se unen para encontrar a Robby. Miguel enfrenta un futuro incierto, y Kreese intenta llevar a Tory de regreso a Cobra Kai.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=3), 3, 'Ahora tendrás que pagar', 'La dañada reputación de Daniel afecta las ventas de la concesionaria, y alguien se ofrece a comprarla. Johnny busca dinero para la operación de Miguel.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=3), 4, 'El camino correcto', 'Después de una importante reunión que lo lleva hasta Japón, Daniel regresa a Okinawa, la ciudad natal del señor Miyagi. Johnny intenta estrechar su vínculo con Robby.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=3), 5, 'Miyagi-Do', 'En Okinawa, Daniel se encuentra con una vieja amiga y con un viejo enemigo con mucho para enseñarle. La rivalidad de los dojos se vuelve muy peligrosa.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=3), 6, 'El rey', 'Miguel ayuda a Johnny a redactar el mensaje perfecto para enviar por una red social. Kreese busca nuevos reclutas, mientras Daniel y Amanda intentan cerrar Cobra Kai.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=3), 7, 'Obstáculos', 'Daniel pasa tiempo con Sam, quien no puede perdonarse por lo sucedido en la escuela. Johnny planea abrir un nuevo dojo, pero encontrarle un nombre no será tarea sencilla.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=3), 8, 'El bueno, el malo y el incansable', 'Cuando se enteran de la cancelación del Torneo de Karate All Valley, Daniel, Johnny y Kreese asisten a una reunión del ayuntamiento para salvarlo.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=3), 9, 'Feel The Night', 'Llega la Navidad al valle, y el romance está en el aire. Daniel y Miguel descubren que tienen algo inesperado en común, y los reclutas de Cobra Kai emprenden una misión.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=3), 10, '19 de diciembre', 'En una fiesta del club de campo, las viejas heridas comienzan a cicatrizar, pero un brutal ataque de los alumnos de Kreese da lugar a nuevas traiciones y nuevas alianzas.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=4), 1, '¡Comencemos!', 'Johnny y Daniel combinan sus dojos, pero sus estilos opuestos chocan de inmediato. Kreese intenta persuadir a un antiguo socio para que se una a Cobra Kai.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=4), 2, 'Primero estar de pie', 'Johnny aprende estrategias defensivas mientras Daniel practica cómo atacar. Amanda confronta a Tory. Kenny, el nuevo alumno, es acosado en la escuela.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=4), 3, 'Luego aprender a volar', 'Kenny intenta entrenar en Cobra Kai con el apoyo de Robby, mientras Johnny le pide a Sam que aprenda a confiar... en sí misma.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=4), 4, 'Bicefalia', 'Kreese lleva a Terry de vuelta a Cobra Kai, pero su antiguo socio no quiere repetir la historia. Daniel entrena a Miguel... y Johnny no puede controlar los celos.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=4), 5, 'Punto de partido', 'El dojo de Johnny y Daniel, así como su frágil alianza, quedan al borde del colapso cuando estos aceptan participar en un enfrentamiento entre sus sensei.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=4), 6, 'Las patadas consiguen damas', 'Un gran cambio en el próximo torneo lleva a Johnny a apresurarse para encontrar una nueva alumna para el dojo. Tory debe pedirles un favor a los LaRusso.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=4), 7, 'Campos minados', 'Daniel invita a Anthony a unirse a Miyagi‑Do, pero descubre que no conoce a su hijo tanto como pensaba. Miguel se entera de la verdad sobre Johnny y Carmen.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=4), 8, 'Empieza la fiesta', 'Miguel y Sam están emocionados por el baile escolar..., hasta que otra pareja aparece inesperadamente. Terry lleva a Johnny a un lugar muy familiar.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=4), 9, 'La caída', 'El torneo anual empieza y varios dojos compiten para ser los campeones... y ajustar cuentas personales.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=4), 10, 'El ascenso', 'El torneo llega a un final impactante: sus consecuencias afectan a los participantes... y dos campeones afrontan futuros inciertos.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=5), 1, 'Muy lejos de casa', 'El nuevo aliado y compañero de casa de Daniel pone a prueba la paciencia de Amanda. Miguel busca a su padre en México. Terry empieza a transformar Cobra Kai.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=5), 2, 'Topo', 'Chozen y Daniel idean un arriesgado plan contra Terry. En México, Robby y Johnny buscan a Miguel, quien descubre la verdad sobre su padre.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=5), 3, 'Jugar con fuego', 'Aparece otro enemigo del pasado de Daniel. Después de un día en el spa y un poco de reflexión, Sam toma una decisión sobre su futuro con Miguel.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=5), 4, 'Caída en espiral', 'El romance de Johnny y Carmen va viento en popa, mientras Daniel y Amanda sufren las artimañas de Terry. Las diferencias del grupo salen a la luz en el parque acuático.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=5), 5, 'Medidas extremas', 'Daniel confía en un amigo... y en un amienemigo. La tensión aumenta para Miguel y Robby. Regresa una cara conocida.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=5), 6, 'Uróboros', 'Terry recluta a un experto en el Camino del Puño. Daniel evita una pelea, a diferencia de Johnny y Chozen. En la cárcel, Kreese enfrenta los traumas del pasado.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=5), 7, 'Huevos podridos', 'Terry y Kim anuncian un desafío brutal, mientras Chozen tiene otro tipo de enseñanzas para sus alumnos. Johnny y Daniel le exigen respuestas a Kreese.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=5), 8, 'Taikai', 'Un ansiado puesto en un torneo internacional enciende una pelea entre dojos. Se pone a prueba la lealtad de Tory. Sam se resiste a dejar ir a Miguel.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=5), 9, 'Sobrevivientes', 'Tory paga por su desacato. Mantaraya lucha con su conciencia. Una noche de celebración en la ciudad da un vuelco para Johnny, Daniel y Chozen.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=5), 10, 'La cabeza de la serpiente', 'Se desata una noche de combate cuando Johnny, Daniel, Chozen y los estudiantes suman sus fuerzas y destrezas para exponer y derrotar a Terry.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=6), 1, 'Tiempos de paz', 'Los estudiantes del Miyagi‑do no logran dejar atrás sus antiguas rivalidades mientras entrenan para el Sekai Taikai. Johnny y Chozen tienen distintas ideas para reinventar el dojo.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=6), 2, 'El premio', 'Kreese debe superar una prueba peligrosa para mostrar su valía. Daniel le da una mano a Johnny mientras los jóvenes piensan en su futuro después de la escuela.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=6), 3, 'Pijamada', 'Daniel hace un descubrimiento que lo hace cuestionar todas sus creencias. Johnny busca cómo devolverles a Sam y Tory su actitud. Se revela la sede del torneo.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=6), 4, 'Subestimados', 'Daniel y Johnny invitan a un nuevo senséi para que evalúe a sus estudiantes. El deseo de llegar al Sekai Taikai hace que incluso las amistades más firmes se pongan a prueba.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=6), 5, 'Lo mejor de lo mejor', 'Los mejores estudiantes del Miyagi‑do se enfrentan para elegir al capitán, pero una tragedia terrible cambia las cosas. Kreese revela su sorpresa final.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=6), 6, 'Benvinguts a Barcelona', 'El Sekai Taikai comienza, pero una traición amenaza con desestabilizar a Miyagi‑Do. Todos se llevan una sorpresa en el dramático primer encuentro.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=6), 7, 'Pelear a cara de perro', 'Daniel se pone en peligro al indagar en el pasado del señor Miyagi. Miguel duda sobre la concentración de Robby. Sam observa una conducta inapropiada en un rival.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=6), 8, 'Sospechas en el aire', 'Una crisis personal afecta profundamente a Miguel y a Johnny. Chozen une fuerzas con una persona inesperada para encontrar a sus alumnos, y ambos terminan descubriendo algo más.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=6), 9, 'Sangre por sangre', '¿Quién pasará a la siguiente ronda en el combate de eliminación? ¿Miyagi‑Do o Cobra Kai? Una revelación impactante sacude a Daniel.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=6), 10, 'Eunjangdo', 'Daniel y Johnny entrenan a sus capitanes en lugares históricos de Barcelona. Pero un golpe bajo en las semifinales desata una pelea sin precedentes.')
;
