-- Paises, no se que hacer para las descripciones

INSERT INTO Pais
    (nombre) VALUES
    ('Alemania'),
    ('Argentina'),
    ('Australia'),
    ('Brazil'),
    ('Canada'),
    ('Chile'),
    ('Colombia'),
    ('Francia'),
    ('India'),
    ('Indonesia'),
    ('Italia'),
    ('Japon'),
    ('Corea del Sur'),
    ('Mexico'),
    ('Peru'),
    ('Polonia'),
    ('Espana'),
    ('Turquia'),
    ('Estados Unidos'),
    ('Venezuela')
;

INSERT INTO Ciudad
    (nombre, id_pais) VALUES
    ('Cologne', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Alemania')),
    ('Hamburg', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Alemania')),
    ('Munich', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Alemania')),
    ('Stuttgart', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Alemania')),
    ('Wuppertal', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Alemania')),
    ('Rosario', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Argentina')),
    ('Buenos Aires', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Argentina')),
    ('Cordoba', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Argentina')),
    ('Corrientes', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Argentina')),
    ('Santa Fe', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Argentina')),
    ('Adelaide', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Australia')),
    ('Perth', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Australia')),
    ('Brisbane', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Australia')),
    ('Canberra', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Australia')),
    ('Cranbourne', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Australia')),
    ('Sao Luis', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Brazil')),
    ('Campinas', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Brazil')),
    ('Rio de Janeiro', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Brazil')),
    ('Belem', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Brazil')),
    ('Guarulhos', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Brazil')),
    ('Ottawa', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Canada')),
    ('Edmonton', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Canada')),
    ('Calgary', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Canada')),
    ('Vancouver', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Canada')),
    ('Victoria', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Canada')),
    ('La Florida', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Chile')),
    ('Maipu', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Chile')),
    ('Puente Alto', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Chile')),
    ('Santiago', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Chile')),
    ('Concepcion', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Chile')),
    ('Barranquilla', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Colombia')),
    ('Cali', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Colombia')),
    ('Medellin', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Colombia')),
    ('Palmira', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Colombia')),
    ('Neiva', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Colombia')),
    ('Paris', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Francia')),
    ('Toulouse', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Francia')),
    ('Lyon', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Francia')),
    ('Marseille', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Francia')),
    ('Bordeaux', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Francia')),
    ('Bareilly', (SELECT id_pais FROM Pais WHERE nombre LIKE 'India')),
    ('Kota', (SELECT id_pais FROM Pais WHERE nombre LIKE 'India')),
    ('Raipur', (SELECT id_pais FROM Pais WHERE nombre LIKE 'India')),
    ('Jodhpur', (SELECT id_pais FROM Pais WHERE nombre LIKE 'India')),
    ('Vijayawada', (SELECT id_pais FROM Pais WHERE nombre LIKE 'India')),
    ('Bogor', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Indonesia')),
    ('Bandar Lampung', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Indonesia')),
    ('Cilacap', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Indonesia')),
    ('Batam Centre', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Indonesia')),
    ('Sumedang', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Indonesia')),
    ('Milan', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Italia')),
    ('Rome', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Italia')),
    ('Florence', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Italia')),
    ('Bologna', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Italia')),
    ('Genoa', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Italia')),
    ('Sendai', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Japon')),
    ('Hiroshima', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Japon')),
    ('Saitama', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Japon')),
    ('Kyoto', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Japon')),
    ('Osaka', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Japon')),
    ('Changwon', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Corea del Sur')),
    ('Goyang', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Corea del Sur')),
    ('Tongjin', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Corea del Sur')),
    ('Ulsan', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Corea del Sur')),
    ('Suwon', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Corea del Sur')),
    ('Morelia', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Mexico')),
    ('Ciudad Nezahualcoyotl', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Mexico')),
    ('Nezahualcoyotl', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Mexico')),
    ('Mexicali', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Mexico')),
    ('Juarez', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Mexico')),
    ('Arequipa', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Peru')),
    ('Lima', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Peru')),
    ('Iquitos', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Peru')),
    ('Huancayo', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Peru')),
    ('Callao', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Peru')),
    ('Warsaw', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Polonia')),
    ('Szczecin', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Polonia')),
    ('Gdansk', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Polonia')),
    ('Poznan', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Polonia')),
    ('Lodz', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Polonia')),
    ('Sevilla', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Espana')),
    ('Valencia', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Espana')),
    ('Barcelona', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Espana')),
    ('Santa Cruz', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Espana')),
    ('Palma', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Espana')),
    ('Denizli', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Turquia')),
    ('Balikesir', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Turquia')),
    ('Samsun', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Turquia')),
    ('Kayseri', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Turquia')),
    ('Istanbul', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Turquia')),
    ('Memphis', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Estados Unidos')),
    ('Richmond', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Estados Unidos')),
    ('Raleigh', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Estados Unidos')),
    ('Salt Lake City', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Estados Unidos')),
    ('Nashville', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Estados Unidos')),
    ('San Cristobal', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Venezuela')),
    ('Barquisimeto', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Venezuela')),
    ('Valencia', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Venezuela')),
    ('Maracaibo', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Venezuela')),
    ('Caracas', (SELECT id_pais FROM Pais WHERE nombre LIKE 'Venezuela'))
;

    
-- Contenido
INSERT INTO Contenido
    (annio_lanzamiento, nombre, es_contenido_original) VALUES
    (2024, 'Cobra Kai', TRUE)
;


-- Serie
INSERT INTO Serie
    (id_contenido, num_episodios, descripcion) VALUES
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), 60, 'Enemigos acérrimos. Dojos rivales. Sangre nueva. Daniel y Johnny reviven viejas rivalidades en esta secuela de las películas de «Karate Kid».')
;


-- Temporada, usar get_season
INSERT INTO Temporada
    (id_contenido, numero, descripcion) VALUES
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), 1,'Décadas después del torneo que les cambió la vida, se reaviva la rivalidad entre Johnny y Daniel. Esta secuela continúa la historia de las películas de Karate Kid.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), 2,'Johnny intenta construir una nueva vida, pero alguien del pasado podría alterar su futuro. Daniel abre su Miyagi-do para competir contra Cobra Kai.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), 3,'Con un nuevo sensei al mando del dojo de la serpiente, las batallas se libran en tres frentes. Al igual que Cobra Kai, las viejas rencillas nunca mueren...'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), 4,'Daniel y Johnny deciden unir fuerzas para enfrentar a un enemigo en común, y Kreese busca un aliado en el pasado.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), 5,'Mientras Terry conduce a Cobra Kai hacia un nuevo régimen, Daniel, Johnny y un viejo aliado unen sus fuerzas en una batalla que va más allá del dojo.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), 6,'El mundial de karate se acerca, y Daniel y Johnny trabajan para rearmar el equipo. Pero viejos enemigos y nuevos peligros minan el camino a la gloria.')
;

-- Episodio, usar get_episode
INSERT INTO Episodio
    (id_contenido, id_temporada, numero, nombre, descripcion) VALUES
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=1), 1, 'As degenerado', 'Alcohólico y harto de vivir a la sombra de Daniel, su antiguo rival, Johnny toca fondo y decide reabrir el dojo de karate Cobra Kai.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=1), 2, 'Golpear primero', 'Daniel ve el nuevo dojo Cobra Kai, y eso le trae recuerdos dolorosos. Más tarde, se entera de que Kyler, el chico que le gusta a Sam, fue atacado por un karateca.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=1), 3, 'Esqueleto', 'Con la idea de vigilar a Sam, Daniel se ofrece como chaperón para el baile de Halloween. Johnny intenta conseguir más alumnos para su flamante proyecto.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=1), 4, 'Cobra Kai nunca muere', 'Alguien arruina uno de los carteles de Daniel. La madre de Miguel le prohíbe practicar karate a su hijo, y Johnny recibe una llamada preocupante de la escuela de Robby.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=1), 5, 'Contrapeso', 'Una nueva alumna se suma a Cobra Kai. Entretanto, Daniel piensa en la forma de vengarse de Johnny. Kyler traiciona a Sam, y Miguel la defiende en la escuela.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=1), 6, 'Temblor', 'Tras la pelea de Miguel, se inscriben más alumnos en Cobra Kai, pero Johnny no los recibe de la mejor manera. Para herir a su padre, Robby empieza a trabajar con Daniel.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=1), 7, 'All Valley', 'Johnny debe persuadir al comité del torneo de levantar la prohibición impuesta a Cobra Kai, pero Daniel es uno de los miembros. Miguel y Sam tienen una cita.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=1), 8, 'Muda', 'Mientras Johnny prepara a sus alumnos para el torneo de All Valley, Daniel empieza a entrenar a Robby en el Miyagi-do sin saber que es el hijo de Johnny.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=1), 9, 'Diferentes pero iguales', 'Una discusión hace que Johnny y Daniel revivan el pasado. Los alumnos de Cobra Kai planean vengarse de los chicos populares.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=1), 10, 'Piedad', 'Antes del torneo, Johnny les enseña a sus alumnos la tercera regla de Cobra Kai: sin piedad. Alguien inesperado regresa a la vida de Johnny.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=2), 1, 'Piedad (Parte 2)', 'A pesar de la victoria de Cobra Kai, Johnny quiere cambiar el rumbo del dojo. Daniel abre su propia escuela con dos alumnos: Sam y Robby.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=2), 2, 'Otra vez juntos', 'Daniel les enseña a Sam y a Robby a encontrar el equilibrio. Johnny impresiona a Kreese con una técnica de entrenamiento creativa pero riesgosa.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=2), 3, 'Hielo y fuego', 'Cuando Miguel descubre que Robby es hijo de Johnny, el sensei reconoce sus falencias paternales. En busca de más alumnos, Daniel hace una demostración en un festival.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=2), 4, 'La hora de la verdad', 'Daniel sigue intentando promocionar el Miyagi-do, pero Cobra Kai es el centro de atención. Johnny sospecha que Kreese exagera sus logros.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=2), 5, 'Darlo todo', 'Después de que Eli desafía a Demetri en el centro comercial, Daniel ayuda a Demetri a tener confianza en sí mismo. Johnny se entera de que Robby está viviendo con Daniel.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=2), 6, 'Echa un vistazo a tu derecha', 'Los nuevos alumnos de Daniel aprenden a conciliar sus diferencias. Mientras Johnny disfruta de un viaje con amigos, Kreese impone su autoridad en el dojo.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=2), 7, 'Calma', 'Aunque cada sensei tiene su propio estilo, ambos prueban nuevas técnicas. Johnny confronta a Kreese, y la pasión de Daniel por el Miyagi-do pone en peligro su negocio.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=2), 8, 'Glory of Love', 'A medida que se enciende el romance secreto entre Sam y Robby, se enfría la relación entre Daniel y Amanda. Johnny intenta hallar el amor con ayuda de la tecnología.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=2), 9, 'Pulpo', 'Tras un encuentro imprevisto, Johnny y Daniel deciden darse una tregua. Por el contrario, la tensión acumulada entre los alumnos de ambos se descontrola en una fiesta.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=2), 10, 'Sin piedad', 'El primer día de clases, la rencilla entre Tory y Sam termina explotando en un enfrentamiento de karate que acapara la atención de toda la escuela.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=3), 1, 'Repercusiones', 'Mientras Miguel lucha por su vida y Robby está desaparecido, la comunidad de West Valley no duda en expresar su descontento con lo ocurrido... y con Daniel y Johnny.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=3), 2, '¿La herencia es más fuerte?', 'Daniel y Johnny se unen para encontrar a Robby. Miguel enfrenta un futuro incierto, y Kreese intenta llevar a Tory de regreso a Cobra Kai.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=3), 3, 'Ahora tendrás que pagar', 'La dañada reputación de Daniel afecta las ventas de la concesionaria, y alguien se ofrece a comprarla. Johnny busca dinero para la operación de Miguel.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=3), 4, 'El camino correcto', 'Después de una importante reunión que lo lleva hasta Japón, Daniel regresa a Okinawa, la ciudad natal del señor Miyagi. Johnny intenta estrechar su vínculo con Robby.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=3), 5, 'Miyagi-Do', 'En Okinawa, Daniel se encuentra con una vieja amiga y con un viejo enemigo con mucho para enseñarle. La rivalidad de los dojos se vuelve muy peligrosa.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=3), 6, 'El rey', 'Miguel ayuda a Johnny a redactar el mensaje perfecto para enviar por una red social. Kreese busca nuevos reclutas, mientras Daniel y Amanda intentan cerrar Cobra Kai.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=3), 7, 'Obstáculos', 'Daniel pasa tiempo con Sam, quien no puede perdonarse por lo sucedido en la escuela. Johnny planea abrir un nuevo dojo, pero encontrarle un nombre no será tarea sencilla.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=3), 8, 'El bueno, el malo y el incansable', 'Cuando se enteran de la cancelación del Torneo de Karate All Valley, Daniel, Johnny y Kreese asisten a una reunión del ayuntamiento para salvarlo.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=3), 9, 'Feel The Night', 'Llega la Navidad al valle, y el romance está en el aire. Daniel y Miguel descubren que tienen algo inesperado en común, y los reclutas de Cobra Kai emprenden una misión.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=3), 10, '19 de diciembre', 'En una fiesta del club de campo, las viejas heridas comienzan a cicatrizar, pero un brutal ataque de los alumnos de Kreese da lugar a nuevas traiciones y nuevas alianzas.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=4), 1, '¡Comencemos!', 'Johnny y Daniel combinan sus dojos, pero sus estilos opuestos chocan de inmediato. Kreese intenta persuadir a un antiguo socio para que se una a Cobra Kai.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=4), 2, 'Primero estar de pie', 'Johnny aprende estrategias defensivas mientras Daniel practica cómo atacar. Amanda confronta a Tory. Kenny, el nuevo alumno, es acosado en la escuela.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=4), 3, 'Luego aprender a volar', 'Kenny intenta entrenar en Cobra Kai con el apoyo de Robby, mientras Johnny le pide a Sam que aprenda a confiar... en sí misma.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=4), 4, 'Bicefalia', 'Kreese lleva a Terry de vuelta a Cobra Kai, pero su antiguo socio no quiere repetir la historia. Daniel entrena a Miguel... y Johnny no puede controlar los celos.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=4), 5, 'Punto de partido', 'El dojo de Johnny y Daniel, así como su frágil alianza, quedan al borde del colapso cuando estos aceptan participar en un enfrentamiento entre sus sensei.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=4), 6, 'Las patadas consiguen damas', 'Un gran cambio en el próximo torneo lleva a Johnny a apresurarse para encontrar una nueva alumna para el dojo. Tory debe pedirles un favor a los LaRusso.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=4), 7, 'Campos minados', 'Daniel invita a Anthony a unirse a Miyagi‑Do, pero descubre que no conoce a su hijo tanto como pensaba. Miguel se entera de la verdad sobre Johnny y Carmen.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=4), 8, 'Empieza la fiesta', 'Miguel y Sam están emocionados por el baile escolar..., hasta que otra pareja aparece inesperadamente. Terry lleva a Johnny a un lugar muy familiar.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=4), 9, 'La caída', 'El torneo anual empieza y varios dojos compiten para ser los campeones... y ajustar cuentas personales.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=4), 10, 'El ascenso', 'El torneo llega a un final impactante: sus consecuencias afectan a los participantes... y dos campeones afrontan futuros inciertos.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=5), 1, 'Muy lejos de casa', 'El nuevo aliado y compañero de casa de Daniel pone a prueba la paciencia de Amanda. Miguel busca a su padre en México. Terry empieza a transformar Cobra Kai.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=5), 2, 'Topo', 'Chozen y Daniel idean un arriesgado plan contra Terry. En México, Robby y Johnny buscan a Miguel, quien descubre la verdad sobre su padre.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=5), 3, 'Jugar con fuego', 'Aparece otro enemigo del pasado de Daniel. Después de un día en el spa y un poco de reflexión, Sam toma una decisión sobre su futuro con Miguel.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=5), 4, 'Caída en espiral', 'El romance de Johnny y Carmen va viento en popa, mientras Daniel y Amanda sufren las artimañas de Terry. Las diferencias del grupo salen a la luz en el parque acuático.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=5), 5, 'Medidas extremas', 'Daniel confía en un amigo... y en un amienemigo. La tensión aumenta para Miguel y Robby. Regresa una cara conocida.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=5), 6, 'Uróboros', 'Terry recluta a un experto en el Camino del Puño. Daniel evita una pelea, a diferencia de Johnny y Chozen. En la cárcel, Kreese enfrenta los traumas del pasado.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=5), 7, 'Huevos podridos', 'Terry y Kim anuncian un desafío brutal, mientras Chozen tiene otro tipo de enseñanzas para sus alumnos. Johnny y Daniel le exigen respuestas a Kreese.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=5), 8, 'Taikai', 'Un ansiado puesto en un torneo internacional enciende una pelea entre dojos. Se pone a prueba la lealtad de Tory. Sam se resiste a dejar ir a Miguel.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=5), 9, 'Sobrevivientes', 'Tory paga por su desacato. Mantaraya lucha con su conciencia. Una noche de celebración en la ciudad da un vuelco para Johnny, Daniel y Chozen.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=5), 10, 'La cabeza de la serpiente', 'Se desata una noche de combate cuando Johnny, Daniel, Chozen y los estudiantes suman sus fuerzas y destrezas para exponer y derrotar a Terry.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=6), 1, 'Tiempos de paz', 'Los estudiantes del Miyagi‑do no logran dejar atrás sus antiguas rivalidades mientras entrenan para el Sekai Taikai. Johnny y Chozen tienen distintas ideas para reinventar el dojo.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=6), 2, 'El premio', 'Kreese debe superar una prueba peligrosa para mostrar su valía. Daniel le da una mano a Johnny mientras los jóvenes piensan en su futuro después de la escuela.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=6), 3, 'Pijamada', 'Daniel hace un descubrimiento que lo hace cuestionar todas sus creencias. Johnny busca cómo devolverles a Sam y Tory su actitud. Se revela la sede del torneo.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=6), 4, 'Subestimados', 'Daniel y Johnny invitan a un nuevo senséi para que evalúe a sus estudiantes. El deseo de llegar al Sekai Taikai hace que incluso las amistades más firmes se pongan a prueba.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=6), 5, 'Lo mejor de lo mejor', 'Los mejores estudiantes del Miyagi‑do se enfrentan para elegir al capitán, pero una tragedia terrible cambia las cosas. Kreese revela su sorpresa final.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=6), 6, 'Benvinguts a Barcelona', 'El Sekai Taikai comienza, pero una traición amenaza con desestabilizar a Miyagi‑Do. Todos se llevan una sorpresa en el dramático primer encuentro.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=6), 7, 'Pelear a cara de perro', 'Daniel se pone en peligro al indagar en el pasado del señor Miyagi. Miguel duda sobre la concentración de Robby. Sam observa una conducta inapropiada en un rival.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=6), 8, 'Sospechas en el aire', 'Una crisis personal afecta profundamente a Miguel y a Johnny. Chozen une fuerzas con una persona inesperada para encontrar a sus alumnos, y ambos terminan descubriendo algo más.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=6), 9, 'Sangre por sangre', '¿Quién pasará a la siguiente ronda en el combate de eliminación? ¿Miyagi‑Do o Cobra Kai? Una revelación impactante sacude a Daniel.'),
    ((SELECT id_contenido FROM Contenido WHERE nombre='Cobra Kai'), (SELECT id_temporada FROM Temporada WHERE numero=6), 10, 'Eunjangdo', 'Daniel y Johnny entrenan a sus capitanes en lugares históricos de Barcelona. Pero un golpe bajo en las semifinales desata una pelea sin precedentes.')
;
